Repository Azure/azure-libraries-for-net, pull requests merged in 2019-07, with the labels that each got.

#679 Avoid exception for existing tags and overwrite
  src/ResourceManagement/Compute/VirtualMachineExtensionImpl.cs
  src/ResourceManagement/ContainerRegistry/WebhookImpl.cs
  src/ResourceManagement/ResourceManager/ResourceGroup/ResourceGroupImpl.cs
  src/ResourceManagement/Sql/SqlDatabaseImpl.cs
  src/ResourceManagement/Sql/SqlElasticPoolImpl.cs
Labels: Mgmt, customer-reported

#728 Fix the service bus tests to use basic or standard SKUs
  Samples/ServiceBus/ServiceBusPublishSubscribeAdvanceFeatures.cs
  Samples/ServiceBus/ServiceBusPublishSubscribeBasic.cs
  Samples/ServiceBus/ServiceBusQueueAdvanceFeatures.cs
  Samples/ServiceBus/ServiceBusQueueBasic.cs
  Samples/ServiceBus/ServiceBusWithClaimBasedAuthorization.cs
  Tests/Fluent.Tests/ServiceBus/ServiceBusTests.cs
  Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanCRUDOnSimpleNamespace.json
  Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanCreateDeleteQueueWithNamespace.json
  Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanCreateDeleteTopicWithNamespace.json
  Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanCreateNamespaceThenCRUDOnQueue.json
  Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanCreateNamespaceThenCRUDOnTopic.json
  Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanOperateOnAuthorizationRules.json
  Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanPerformCRUDOnSubscriptions.json
  Tests/Fluent.Tests/SessionRecords/Fluent.Tests.ServiceBus/CanPerformOnNamespaceActions.json
  Tests/Samples.Tests/SessionRecords/Samples.Tests.ServiceBus/PublishSubscribeAdvanceFeaturesTest.json
  Tests/Samples.Tests/SessionRecords/Samples.Tests.ServiceBus/PublishSubscribeBasicTest.json
  Tests/Samples.Tests/SessionRecords/Samples.Tests.ServiceBus/QueueAdvanceFeaturesTest.json
  Tests/Samples.Tests/SessionRecords/Samples.Tests.ServiceBus/QueueBasicTest.json
  Tests/Samples.Tests/SessionRecords/Samples.Tests.ServiceBus/WithClaimBasedAuthorizationTest.json
Labels: Mgmt, Service Bus

#662 Add constructor taking tenant id as parameter for AzureCredentials constructor when using MSI
  src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs
  src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs
Labels: Authorization, Mgmt, customer-reported

#735 Add support for user-assigned MSIs from AppServices to MSITokenProvider
  src/ResourceManagement/ResourceManager/Authentication/MSITokenProvider.cs
Labels: Mgmt
